### ISSUE TITLE
Create correctly,but could not open because of wrong directory

### ISSUE THREAD

**Issue by FujunLiu** [JohnSundell/Playground#13]
The error message:
🚀  Opening \~/Desktop/2018/3/1.playground/...
💥  An error occured: ShellOut encountered an error
Status code: 1
Message: "The file /Users/admin/~/Desktop/2018/3/1.playground does not exist."
Output: ""

/Users/admin/~/Desktop/ is a wrong directory. 
Please correct it.Thanks!

**Comment by JohnSundell** [comment]
Fixed by @Ashton-W in #11

**Comment by dreymonde** [comment]
@JohnSundell the issue still persists:

```
🚀  Opening ~/Desktop/3-5-18.playground/...
💥  An error occured: ShellOut encountered an error
Status code: 1
Message: "The file /Users/oleg/Development/OpenSource/Playground/Sources/~/Desktop/3-5-18.playground does not exist."
Output: ""
```

I investigated and turned out that #12 is responsible for that 🙁

**Comment by JohnSundell** [comment]
@dreymonde Ah, I see. Wanna submit a fix?

**Comment by JohnSundell** [comment]
I'll revert #12 in the meantime, since now all playground creation fails (maybe I should add some CI to this project? 🤔)

**Comment by JohnSundell** [comment]
Alright, now it should work again. Sorry about that folks 🙂

**Comment by dreymonde** [comment]
@JohnSundell great! I think I’ll try to come up with a better fix shortly.

**Comment by JohnSundell** [comment]
@dreymonde That'd be awesome 😄
